[package]
name = "coral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
rustls = "0.20.8"
telnet = "0.2.1"
webpki-roots = "0.22.6"
